### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by lococo14** [lococo14/protospace-33471#1]
https://protospace-33471.herokuapp.com/

**Comment by junkiyamada** [comment]
lococo14様、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下3点の不備が見受けられましたので修正をお願いします！

・ユーザー詳細ページにプロトタイプが表示されていない
→testさんユーザー詳細ページにはtestさんのプロトタイプが表示されるようにしましょう。

・トップページに表示されているプロトタイプの右下にあるユーザー名をクリックした際、プロトタイプ詳細ページに遷移されてしまう
→ユーザー名をクリックした際はユーザー詳細ページに遷移するようにしましょう。

・他のユーザーのプロトタイプ編集ページに遷移できてしまう
→他のユーザーが編集ページに遷移しようとした際は、トップページにリダイレクトされるようにしましょう。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
もう少しです、頑張っていきましょう！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by lococo14** [comment]
修正しました！

**Comment by Nishi0418** [comment]
lococo14さん

ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・New protoアイコンをクリックするとスクショのエラーページに遷移します。
→proto投稿ページに遷移するように修正をお願いします。
<img width="1440" alt="スクリーンショット 2021-01-11 10 13 28" src="https://user-images.githubusercontent.com/51874745/104140687-f8ba8b80-53f5-11eb-8637-d63c4ea7234d.png">


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by lococo14** [comment]
再度修正しましたので、確認をお願いします！

**Comment by Nishi0418** [comment]
lococo14さん

ご提出ありがとうございます！
前回の指摘箇所、ご修正ありがとうございます！
お疲れさまでした。

挙動確認させて頂いたところ、新たに以下の不備が見受けられましたので修正をお願いします！
・proto編集ページにて、記入欄を空欄にして保存を押すと、他の記入欄に記入済みの情報が消えます。
・上記のとき、保存を押すと、以下のようなエラー画面に遷移します。
正しくは、空欄がある状態で保存を押しても記入済みの情報は消えずに、編集ページにとどまります。
<img width="1440" alt="スクリーンショット 2021-01-11 15 01 25" src="https://user-images.githubusercontent.com/51874745/104150867-a9d51c00-541e-11eb-998d-c95b504f3c52.png">


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by lococo14** [comment]
何度も何度も申し訳ありません！再度修正したので、確認お願い致します。

**Comment by Nishi0418** [comment]
lococo14さん
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

ご修正、ありがとうございました。
スピーディーかつ、的確にご修正依頼にご対応くださったこと、素晴らしいと感じました！
最終課題も頑張ってください！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by lococo14** [comment]
ありがとうございました！
